baseURL = "https://fc.181861.xyz/"
languageCode = "zh-CN"
title = "ç¬¬ä¸€æ–‡æ˜"
theme = "blowfish"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "This is my Hugo site"
  [params.author]
    name = "ç¬¬ä¸€æ–‡æ˜"
    
[main]
  # ç¡®ä¿è¿™é‡ŒæŒ‡å‘ä½ çš„å›¾æ ‡
  favicon = "favicon.ico"
  emoji = "ğŸ–¼ï¸" # å¦‚æœæ²¡æœ‰å›¾æ ‡ï¼Œæœ‰äº›åœ°æ–¹ä¼šæ˜¾ç¤ºè¿™ä¸ª emoji
