baseURL = "https://fc.181861.xyz/"
languageCode = "zh-cn"
title = "第一文明"
theme = "papermod"

[params]
  [params.profileMode]
    title = "第一文明"
    subtitle = "欢迎来到第一文明的数字花园"
    imageUrl = "/assets/avatar.png"
    imageTitle = "第一文明"
    imageWidth = 150
    imageHeight = 150
